Change the sc_model field type from unsigned to signed since the model can be set to SB_UNK which has a value of -1.
sb.c:307:8: error: comparison of 0 <= unsigned expression is always true [-Werror,-Wtautological-compare]

ok deraadt@