Fix WITNESS build
sparc64 (and arm mem.c) are the only architectures/places where
RWLOCK_INITIALIZER() is used with static function variables, all other
(mem.c) usages place it into the global scope.

Fix builds with WITNESS enabled for sparc64 and arm by moving physlock
into global scope:

mem.c:93: error: initializer element is not constant
mem.c:93: error: (near initialization for 'physlock.rwl_lock_obj.lo_type')

OK visa